import { Entry, EntryHistory, AdminActionLog, Profile } from '../types/database';

export const INITIAL_MOCK_PROFILES: Profile[] = [
  {
    id: 'owner-uuid-1',
    role: 'owner',
    full_name: 'Saidislom (Do‘kon Egasi)',
    phone: '+998901234567',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'worker-uuid-1',
    role: 'worker',
    full_name: 'Jasur Bek',
    phone: '+998935551122',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'worker-uuid-2',
    role: 'worker',
    full_name: 'Bobur Mirzo',
    phone: '+998977778899',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'worker-uuid-3',
    role: 'worker',
    full_name: 'Anvar Qodirov (Sobiq)',
    phone: '+998909990011',
    is_active: false,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_ENTRIES: Entry[] = [
  {
    id: 'entry-101',
    direction: 'customer',
    party_name: 'Olimjon aka (Qo‘shni)',
    party_phone: '+998901112233',
    amount: 450000,
    status: 'open',
    description: 'Un, yog‘ va shakar olindi',
    due_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0], // muddati o'tgan
    created_by: 'worker-uuid-1',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-102',
    direction: 'customer',
    party_name: 'Dilshod Rahmatov',
    party_phone: '+998934445566',
    amount: 1200000,
    status: 'open',
    description: 'Bayram dasturxoni uchun mahsulotlar',
    due_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    created_by: 'worker-uuid-2',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[2],
  },
  {
    id: 'entry-103',
    direction: 'supplier',
    party_name: '«Vodiy Sut» MCHJ',
    party_phone: '+998712003344',
    amount: 3800000,
    status: 'open',
    description: 'Sut, qaymoq va pishloq partiyasi',
    due_date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0], // muddati o'tgan
    created_by: 'worker-uuid-1',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-104',
    direction: 'supplier',
    party_name: 'Shoxrux Optom Ichimliklar',
    party_phone: '+998991238877',
    amount: 2150000,
    status: 'open',
    description: 'Suv va sharbatlar partiyasi',
    due_date: new Date(Date.now() + 8 * 86400000).toISOString().split('T')[0],
    created_by: 'owner-uuid-1',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
  },
  {
    id: 'entry-105',
    direction: 'customer',
    party_name: 'Farhod Sartarosh',
    party_phone: '+998905556677',
    amount: 280000,
    status: 'paid',
    paid_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    description: 'Choy, kofe va shirinliklar',
    due_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    created_by: 'worker-uuid-1',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-106',
    direction: 'supplier',
    party_name: '«Namangan Non» sexi',
    party_phone: '+998692224455',
    amount: 950000,
    status: 'paid',
    paid_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    description: 'Patir va non yetkazib berish',
    due_date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    created_by: 'worker-uuid-2',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[2],
  },
  {
    id: 'entry-107',
    direction: 'customer',
    party_name: 'Sardor Qassob',
    party_phone: '+998913339900',
    amount: 750000,
    status: 'open',
    description: 'Ziravorlar va salfetkalar',
    due_date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    created_by: 'worker-uuid-2',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[2],
  },
];

export const INITIAL_MOCK_HISTORIES: EntryHistory[] = [
  {
    id: 'hist-1',
    entry_id: 'entry-101',
    changed_by: 'worker-uuid-1',
    changed_by_name: 'Jasur Bek',
    change_type: 'created',
    field_name: null,
    old_value: null,
    new_value: { amount: 350000, party_name: 'Olimjon aka (Qo‘shni)' },
    changes: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'hist-2',
    entry_id: 'entry-101',
    changed_by: 'worker-uuid-1',
    changed_by_name: 'Jasur Bek',
    change_type: 'edited',
    field_name: 'amount',
    old_value: 350000,
    new_value: 450000,
    changes: { amount: { old: 350000, new: 450000 } },
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'hist-3',
    entry_id: 'entry-105',
    changed_by: 'owner-uuid-1',
    changed_by_name: 'Saidislom (Do‘kon Egasi)',
    change_type: 'status_changed',
    field_name: 'status',
    old_value: 'open',
    new_value: 'paid',
    changes: { status: { old: 'open', new: 'paid' } },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_ACTION_LOGS: AdminActionLog[] = [
  {
    id: 'action-1',
    admin_user_id: 'owner-uuid-1',
    admin_name: 'Saidislom (Do‘kon Egasi)',
    action_type: 'edit',
    target_entry_id: 'entry-105',
    summary: 'Mijoz qarzi holati to‘langanga o‘zgartirildi: Farhod Sartarosh (280 000 so‘m)',
    before_data: { status: 'open', paid_at: null },
    after_data: { status: 'paid', paid_at: new Date(Date.now() - 1 * 86400000).toISOString() },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'action-2',
    admin_user_id: 'owner-uuid-1',
    admin_name: 'Saidislom (Do‘kon Egasi)',
    action_type: 'manual_add',
    target_entry_id: 'entry-104',
    summary: 'Yangi yetkazib beruvchi qarzi qo‘lda kiritildi: Shoxrux Optom Ichimliklar (2 150 000 so‘m)',
    after_data: INITIAL_MOCK_ENTRIES[3],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'action-3',
    admin_user_id: 'owner-uuid-1',
    admin_name: 'Saidislom (Do‘kon Egasi)',
    action_type: 'delete',
    target_entry_id: 'entry-old-88',
    summary: 'Mijoz qarzi butunlay o‘chirildi: Rustam aka (150 000 so‘m)',
    deleted_entry_snapshot: {
      id: 'entry-old-88',
      direction: 'customer',
      party_name: 'Rustam aka',
      party_phone: '+998901239988',
      amount: 150000,
      status: 'paid',
      description: 'Xato kiritilgan takroriy yozuv',
      due_date: '2026-08-15',
      paid_at: '2026-08-20T10:00:00Z',
      created_by: 'worker-uuid-1',
      last_edited_by: 'owner-uuid-1',
      created_at: '2026-08-10T12:00:00Z',
      updated_at: '2026-08-20T10:00:00Z',
    },
    deleted_entry_history_snapshot: [
      {
        id: 'hist-old-1',
        entry_id: 'entry-old-88',
        changed_by: 'worker-uuid-1',
        changed_by_name: 'Jasur Bek',
        change_type: 'created',
        created_at: '2026-08-10T12:00:00Z',
      },
    ],
    metadata: { reason: 'Mijoz to‘lagan, lekin adashib qayta kiritilgan yozuv' },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
