import { Entry, EntryHistory, AdminActionLog, Profile } from '../types/database';

export const INITIAL_MOCK_PROFILES: Profile[] = [
  {
    id: 'user-abubakir',
    role: 'worker',
    full_name: 'Abubakir',
    phone: '+998901112233',
    pin_code: '1111',
    avatar_color: 'from-blue-600 to-cyan-600',
    is_active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-muhammad',
    role: 'worker',
    full_name: 'Muhammad',
    phone: '+998902223344',
    pin_code: '2222',
    avatar_color: 'from-emerald-600 to-teal-600',
    is_active: true,
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-saidislom',
    role: 'owner',
    full_name: 'Saidislom (Admin)',
    phone: '+998901234567',
    pin_code: '0000',
    avatar_color: 'from-violet-600 to-purple-600',
    is_active: true,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_MOCK_ENTRIES: Entry[] = [
  {
    id: 'entry-101',
    direction: 'customer',
    party_name: 'Olimjon aka (Qo‘shni)',
    party_phone: '+998901112233',
    amount: 450000,
    status: 'open',
    description: 'Un, yog‘ va shakar olindi',
    due_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0], // muddati o'tgan
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
  },
  {
    id: 'entry-102',
    direction: 'customer',
    party_name: 'Dilshod Rahmatov',
    party_phone: '+998934445566',
    amount: 1200000,
    status: 'open',
    description: 'Bayram dasturxoni uchun mahsulotlar',
    due_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    created_by: 'user-muhammad',
    recorded_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-103',
    direction: 'supplier',
    party_name: '«Vodiy Sut» MCHJ',
    party_phone: '+998712003344',
    amount: 3800000,
    status: 'open',
    description: 'Sut, qaymoq va pishloq partiyasi',
    due_date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0], // muddati o'tgan
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
  },
  {
    id: 'entry-104',
    direction: 'supplier',
    party_name: 'Shoxrux Optom Ichimliklar',
    party_phone: '+998991238877',
    amount: 2150000,
    status: 'open',
    description: 'Suv va sharbatlar partiyasi',
    due_date: new Date(Date.now() + 8 * 86400000).toISOString().split('T')[0],
    created_by: 'user-saidislom',
    recorded_by_name: 'Saidislom (Admin)',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[2],
  },
  {
    id: 'entry-105',
    direction: 'customer',
    party_name: 'Farhod Sartarosh',
    party_phone: '+998905556677',
    amount: 280000,
    status: 'paid',
    paid_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    description: 'Choy, kofe va shirinliklar',
    due_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    confirmed_by: 'user-muhammad',
    confirmed_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
    confirmer_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-106',
    direction: 'supplier',
    party_name: '«Namangan Non» sexi',
    party_phone: '+998692224455',
    amount: 950000,
    status: 'paid',
    paid_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    description: 'Patir va non yetkazib berish',
    due_date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    created_by: 'user-muhammad',
    recorded_by_name: 'Muhammad',
    confirmed_by: 'user-saidislom',
    confirmed_by_name: 'Saidislom (Admin)',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
    confirmer_profile: INITIAL_MOCK_PROFILES[2],
  },
  {
    id: 'entry-107',
    direction: 'customer',
    party_name: 'Sardor Qassob',
    party_phone: '+998913339900',
    amount: 750000,
    status: 'open',
    description: 'Ziravorlar va salfetkalar',
    due_date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    created_by: 'user-muhammad',
    recorded_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-108',
    direction: 'customer',
    party_name: 'Olimjon aka (Qo‘shni)',
    party_phone: '+998901112233',
    amount: 150000,
    status: 'open',
    description: '2 quti choy va konfetlar',
    due_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    created_by: 'user-muhammad',
    recorded_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-109',
    direction: 'customer',
    party_name: 'Olimjon aka (Qo‘shni)',
    party_phone: '+998901112233',
    amount: 90000,
    status: 'paid',
    paid_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    description: 'Sabzavot va non',
    due_date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    confirmed_by: 'user-muhammad',
    confirmed_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
    confirmer_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-110',
    direction: 'customer',
    party_name: 'Sardor Qassob',
    party_phone: '+998913339900',
    amount: 350000,
    status: 'open',
    description: 'Go‘sht uchun yog‘och doskalar va pichoqlar',
    due_date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
  },
  {
    id: 'entry-111',
    direction: 'customer',
    party_name: 'Sardor Qassob',
    party_phone: '+998913339900',
    amount: 200000,
    status: 'paid',
    paid_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    description: 'Tuz va qadoqlash paketlari',
    due_date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    confirmed_by: 'user-muhammad',
    confirmed_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
    confirmer_profile: INITIAL_MOCK_PROFILES[1],
  },
  {
    id: 'entry-112',
    direction: 'customer',
    party_name: 'Javohir (Usta)',
    party_phone: '+998945551122',
    amount: 480000,
    status: 'open',
    description: 'Sement, mix va kraskalar',
    due_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    created_by: 'user-abubakir',
    recorded_by_name: 'Abubakir',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[0],
  },
  {
    id: 'entry-113',
    direction: 'customer',
    party_name: 'Botir aka (Traktorchi)',
    party_phone: '+998971239988',
    amount: 620000,
    status: 'open',
    description: 'Moy, antifriz va filtrlar',
    due_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    created_by: 'user-muhammad',
    recorded_by_name: 'Muhammad',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    creator_profile: INITIAL_MOCK_PROFILES[1],
  },
];

export const INITIAL_MOCK_HISTORIES: EntryHistory[] = [
  {
    id: 'hist-1',
    entry_id: 'entry-101',
    changed_by: 'user-abubakir',
    changed_by_name: 'Abubakir',
    change_type: 'created',
    field_name: null,
    old_value: null,
    new_value: { amount: 350000, party_name: 'Olimjon aka (Qo‘shni)' },
    changes: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'hist-2',
    entry_id: 'entry-101',
    changed_by: 'user-abubakir',
    changed_by_name: 'Abubakir',
    change_type: 'edited',
    field_name: 'amount',
    old_value: 350000,
    new_value: 450000,
    changes: { amount: { old: 350000, new: 450000 } },
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'hist-3',
    entry_id: 'entry-105',
    changed_by: 'user-muhammad',
    changed_by_name: 'Muhammad',
    change_type: 'status_changed',
    field_name: 'status',
    old_value: 'open',
    new_value: 'paid',
    changes: { status: { old: 'open', new: 'paid' } },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_ACTION_LOGS: AdminActionLog[] = [
  {
    id: 'action-1',
    admin_user_id: 'user-muhammad',
    admin_name: 'Muhammad',
    action_type: 'edit',
    target_entry_id: 'entry-105',
    summary: 'Mijoz qarzi to‘landi deb tasdiqlandi: Farhod Sartarosh (280 000 so‘m)',
    before_data: { status: 'open', paid_at: null },
    after_data: { status: 'paid', paid_at: new Date(Date.now() - 1 * 86400000).toISOString(), confirmed_by_name: 'Muhammad' },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'action-2',
    admin_user_id: 'user-saidislom',
    admin_name: 'Saidislom (Admin)',
    action_type: 'manual_add',
    target_entry_id: 'entry-104',
    summary: 'Yangi yetkazib beruvchi qarzi qo‘lda kiritildi: Shoxrux Optom Ichimliklar (2 150 000 so‘m)',
    after_data: INITIAL_MOCK_ENTRIES[3],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'action-3',
    admin_user_id: 'user-saidislom',
    admin_name: 'Saidislom (Admin)',
    action_type: 'delete',
    target_entry_id: 'entry-old-88',
    summary: 'Mijoz qarzi butunlay o‘chirildi: Rustam aka (150 000 so‘m)',
    deleted_entry_snapshot: {
      id: 'entry-old-88',
      direction: 'customer',
      party_name: 'Rustam aka',
      party_phone: '+998901239988',
      amount: 150000,
      status: 'paid',
      description: 'Xato kiritilgan takroriy yozuv',
      due_date: '2026-08-15',
      paid_at: '2026-08-20T10:00:00Z',
      created_by: 'user-abubakir',
      recorded_by_name: 'Abubakir',
      last_edited_by: 'user-saidislom',
      created_at: '2026-08-10T12:00:00Z',
      updated_at: '2026-08-20T10:00:00Z',
    },
    deleted_entry_history_snapshot: [
      {
        id: 'hist-old-1',
        entry_id: 'entry-old-88',
        changed_by: 'user-abubakir',
        changed_by_name: 'Abubakir',
        change_type: 'created',
        created_at: '2026-08-10T12:00:00Z',
      },
    ],
    metadata: { reason: 'Mijoz to‘lagan, lekin adashib qayta kiritilgan yozuv' },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
